CODE = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District Of Columbia': 'DC',
    'Federated States Of Micronesia': 'FM',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Marshall Islands': 'MH',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands': 'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Palau': 'PW',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
  }


CODE_R =  {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AS': 'American Samoa',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'DC': 'District Of Columbia',
    'FM': 'Federated States Of Micronesia',
    'FL': 'Florida',
    'GA': 'Georgia',
    'GU': 'Guam',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MH': 'Marshall Islands',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'MP': 'Northern Mariana Islands',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PW': 'Palau',
    'PA': 'Pennsylvania',
    'PR': 'Puerto Rico',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VI': 'Virgin Islands',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming'
  }

SAMPLE =  {'AL': [0, 0, 0], 'AK': [0, 0, 0], 'AS': [0, 0, 0], 'AZ': [0, 0, 0], 'AR': [0, 0, 0], 'CA': [0, 0, 0], 'CO': [0, 0, 0], 'CT': [0, 0, 0], 'DE': [0, 0, 0], 'DC': [0, 0, 0], 'FM': [0, 0, 0], 'FL': [0, 0, 0], 'GA': [0, 0, 0], 'GU': [0, 0, 0], 'HI': [0, 0, 0], 'ID': [0, 0, 0], 'IL': [0, 0, 0], 'IN': [0, 0, 0], 'IA': [0, 0, 0], 'KS': [0, 0, 0], 'KY': [0, 0, 0], 'LA': [0, 0, 0], 'ME': [0, 0, 0], 'MH': [0, 0, 0], 'MD': [0, 0, 0], 'MA': [0, 0, 0], 'MI': [0, 0, 0], 'MN': [0, 0, 0], 'MS': [0, 0, 0], 'MO': [0, 0, 0], 'MT': [0, 0, 0], 'NE': [0, 0, 0], 'NV': [0, 0, 0], 'NH': [0, 0, 0], 'NJ': [0, 0, 0], 'NM': [0, 0, 0], 'NY': [0, 0, 0], 'NC': [0, 0, 0], 'ND': [0, 0, 0], 'MP': [0, 0, 0], 'OH': [0, 0, 0], 'OK': [0, 0, 0], 'OR': [0, 0, 0], 'PW': [0, 0, 0], 'PA': [0, 0, 0], 'PR': [0, 0, 0], 'RI': [0, 0, 0], 'SC': [0, 0, 0], 'SD': [0, 0, 0], 'TN': [0, 0, 0], 'TX': [0, 0, 0], 'UT': [0, 0, 0], 'VT': [0, 0, 0], 'VI': [0, 0, 0], 'VA': [0, 0, 0], 'WA': [0, 0, 0], 'WV': [0, 0, 0], 'WI': [0, 0, 0], 'WY': [0, 0, 0]}